### ISSUE TITLE
First level of the game: Suggestions

### ISSUE THREAD

**Issue by TheAdnan** [TheAdnan/Kirbas-100000#2]
Suggest your ideas and we can discuss here.

**Comment by shubhamjadon** [comment]
Hello Adnan,
 I am one of your students whom you chose to work on your Kirbas-100000 in CMoC.
I was curious to know that whether you have thought anything about gameplay story for your game or not.
If you haven't then please let me know because i have planned a story depending on which we can start making our game levels.

**Comment by TheAdnan** [comment]
@shubhamjadon I haven't, what was your idea?

**Comment by shubhamjadon** [comment]
@TheAdnan  My idea was that to provide people jobs as promised kirbas decides to tell his peoples to learn specific skills according to which he can provide them jobs as in empire jobs were there but only problem was that his peoples didn't had desired skills because there education system was ruled by a demon(or whatever)(and also that demon was very much respected in the empire and was considered as a well-wisher of empire ) who didn't wanted to teach people those skills as that would require too much money and he would have nothing to put in his pocket(i mean corruption) .So in  first chapter we can make kirbas journey to prove that that demon is corrupt and doesn't want anyone's benifit or good.
For first chapter we can make kirbas travelling through different stages fighting demons man and in last we can make a fight b/w kirbas and demon and prove to public that demon is corrupt which will end first chapter.
We can also continue this with further chapters and new problems.....

**Comment by axios047** [comment]
Hey, @TheAdnan @shubhamjadon 
I am another student you chose for CMoC.
@shubhamjadon I love your idea. I was thinking if we could make the gameplay like [cuphead](http://www.cupheadgame.com/). A side scroller + platformer with boss battles and such.

We could divide the map into districts. Each district will have its own challenges and puzzles. Like Kirbas would go to houses(checkpoints) and complete puzzles. Also KIRBAS would need to destroy a stronghold per district of the **demon ruler** by BOSS BATTLES.
